### PR TITLE
Update solutions.yml

### PR DESCRIPTION
**Pull request by yesplease**
Changing copy from "A/B testing platform" to "A/B testing solution"

### CODE REVIEW

**Comment by yesplease** [comment]
@KarenLoughrey one word change on this. thanks!

**Comment by KarenLoughrey** [comment]
@yesplease In progress! Should be in tomorrow. Will let you know as soon as translations are in.

**Comment by KarenLoughrey** [comment]
@yesplease Translations are done!

**Comment by yesplease** [comment]
@KarenLoughrey Thank you!

**Comment by bhamodi** [comment]
LGTM @yesplease! :)

**Pull request merged**
