### PR TITLE
Add Benchmark Report to /Resources

### PR DESCRIPTION
**Pull request by srusonis**
Adding new file to resources page

@stewsmith Could you help check this out to see if it looks good?

### CODE REVIEW

**Comment by stewsmith** [comment]
@srusonis Just remember you need to put `index.hbs` inside a folder named `benchmark-q22015`. I went ahead and did that.

**Comment by srusonis** [comment]
@stewsmith thanks for the reminder - totally skipped that step.

Thanks for sending over the staging link - I have to swap out the image

**Comment by srusonis** [comment]
@stewsmith Just updated the image so we can close that out - let's take a look at staging and hopefully we'll be good to go

**Comment by stewsmith** [comment]
LGTM

**Comment by srusonis** [comment]
@stewsmith SGTM, let's close this branch!

**Comment by stewsmith** [comment]
Thanks @srusonis we're all done here!

**Pull request merged**
