### PR TITLE
Add robots.txt to marketing website

### PR DESCRIPTION
**Pull request by arthuracs**
This is for https://optimizely.atlassian.net/browse/MKT-1712

@stewsmith can you review? I tested this locally and it works at http://localhost:9000/dist/robots.txt but not sure if it's the correct place to add this.

cc: @jrietveld @ihsekat

### CODE REVIEW

**Comment by dtothefp** [comment]
@arthuracs I think this shouldn't go in the assets directory but should just be in the root of `website` and we can copy it from there

**Comment by stewsmith** [comment]
@arthuracs I agree with @dtothefp

**Comment by arthuracs** [comment]
@dtothefp @stewsmith ok, no problem. Like this?

**Comment by ihsekat** [comment]
LGTM, what do you think @stewsmith?

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
