### PR TITLE
Updated Adept Partner Logo

### PR DESCRIPTION
**Pull request by kellyfinn**
@dtothefp @stewsmith @julieritchie 
This is ready

### CODE REVIEW

**Comment by stewsmith** [comment]
@kellyfinn I'm not sure what that timestamp is doing on the end of that image url. Could you use this url for the image instead?

`//d1qmdf3vop2l07.cloudfront.net/optimizely-marketer-assets.cloudvent.net/raw/partner-logos/solutions/adept.png`

**Comment by kellyfinn** [comment]
@stewsmith I wasn't sure why the time stamp was there either but Julie told me to use the "Copy Image URL" in CloudCannon which includes the timestamp. Where would I find the link you suggest? Thanks for the help!

**Comment by stewsmith** [comment]
This is what I did on cloudcannon to get the link.

**Comment by kellyfinn** [comment]
@stewsmith Thanks, got it. Updated.

**Comment by stewsmith** [comment]
LGTM :hamburger:

**Pull request merged**
