### PR TITLE
Create Parse.ly listing in Partner Directory

### PR DESCRIPTION
**Pull request by clarissabee**

### CODE REVIEW

**Comment by clarissabee** [comment]
@julieritchie Here's the PR for Parsely! I will forward logo via e-mail shortly. KB article is still not ready, but will add that soon as it is.

**Comment by kellyfinn** [comment]
@stewsmith @dtothefp @clarissabee @julieritchie 
I've updated the logo... I'm not sure why this partner is already live (https://www.optimizely.com/partners/technology/parsely/)? Preview looks good, should be ready.

**Comment by kellyfinn** [comment]
@clarissabee I think what happened here is that the changes were made to Master branch by mistake. Instead, they should have been made to cbukhan/partnerdirectory-add-parsely.

Looks good to me on live site however, logo is updated.

**Comment by dtothefp** [comment]
@clarissabee @kellyfinn this branch has some major problems so I created a new one. Please review here

https://github.com/optimizely/marketing-website/pull/959

**Pull request closed without merging**
