### PR TITLE
New technology partner: Amplitude

### PR DESCRIPTION
**Pull request by kellyfinn**

### CODE REVIEW

**Comment by kellyfinn** [comment]
@julieritchie Lmk if I should get this live or wait for confirmation on the summary. Thanks

**Comment by julieritchie** [comment]
@kellyfinn  this is good to go. Thanks!

**Comment by stewsmith** [comment]
@julieritchie @kellyfinn Is this ready for eng review?

**Comment by kellyfinn** [comment]
Yes this is ready @stewsmith @julieritchie @dtothefp

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
