### PR TITLE
Update global_feature_list.yml

### PR DESCRIPTION
**Pull request by teeyoutan**
modifying for android launch

### CODE REVIEW

**Comment by teeyoutan** [comment]
@KarenLoughrey  FYI

**Comment by KarenLoughrey** [comment]
@teeyoutan Translations are in progress, will let you know as soon as they're ready (should be about 48 hrs).

**Comment by stewsmith** [comment]
@KarenLoughrey I've updated the footer copy per [the ticket](https://optimizely.atlassian.net/browse/PMM-177). This may also need translation.

**Comment by KarenLoughrey** [comment]
@stewsmith @teeyoutan Translations are done. Having a couple of issues with the iOS --> Mobile (translations are showing up on staging, but not on live pages), but I think we can go ahead and merge and I'll look into that .

**Comment by stewsmith** [comment]
@KarenLoughrey Okay thanks. Deploying now.

**Pull request merged**
