### PR TITLE
Create Lytics Listing in Partner Directory

### PR DESCRIPTION
**Pull request by clarissabee**
@dtothefp @julieritchie Trying this again, since it looks like the branch on my last try was messy. Let me know if this works.

Also, heads up that for the logo, I put in the link from Cloud Cannon, but I'm not sure if this is the correct way to add the logo. If not, please let me know how to do so. Thanks!

### CODE REVIEW

**Comment by dtothefp** [comment]
@clarissabee there were a couple problems. One is that you put the `Lytics` file in the root of the `partners/technology` directory. This won't work because what creates the url path to the page is the name of the directory it is in. Also, our build process will not pick up a file with no file extension.  The proper convention would be:

- `/partners/technology/<company_name>/index.hbs`
- not `/partners/technology/<company_name>

Also, please make sure not to capitalize file names. You can see the convention [here](https://github.com/optimizely/marketing-website/tree/master/website/partners/technology). Also, notice in that link there are a few directories that are capitalized, which is incorrect and I'm going to fix it.

One other problem is you had the wrong url for `lyticis`.  You have `www.lytics.com` and the url is `http://www.getlytics.com`. I've gone ahead and made all the necessary fixes so if @teeyoutan approves then we can merge it. Also, @julieritchie isn't trained on the CMS yet or a collaborator on the repo so you should have Chris T do the reviews for now.

Sorry for the long explanation. We want this stuff to be easy for you and your team so if you have any questions let us know

**Comment by julieritchie** [comment]
hi @dtothefp I reviewed this and needed to resize and reupload the logo. everything else looks good. thanks for your help with the changes you made to this!!

**Comment by julieritchie** [comment]
@dtothefp or @stewsmith bump

**Comment by stewsmith** [comment]
@julieritchie Thanks, looking now.

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
