### PR TITLE
Fix stats comparison

### PR DESCRIPTION
**Pull request by nchilada**
I'm not sure why we're making such a misleading comparison.

BTW the footnote doesn't actually show up.  There's just a hidden div with strangely munged text...

### CODE REVIEW

**Comment by dtothefp** [comment]
LGTM

**Comment by robinpam** [comment]
@dtothefp : Can we please reverse this PR? We want to keep the copy the old way. Thanks.

**Comment by nchilada** [comment]
@robinpam I don't understand how we can justify that comparison.  It's misleading.

**Comment by robinpam** [comment]
Let's talk about it in person. We can't be making changes to the website without running them through marketing first either.

**Comment by nchilada** [comment]
@robinpam There was an email about it, but sure, we should talk in person.

**Pull request merged**
