### PR TITLE
Change homepage copy

### PR DESCRIPTION
**Pull request by stewsmith**

### CODE REVIEW

**Comment by stewsmith** [comment]
@KarenLoughrey This is ready for translation.

**Comment by KarenLoughrey** [comment]
Translations in progress! Hope to have them back tomorrow...will keep you posted. :)

**Comment by KarenLoughrey** [comment]
qq @stewsmith Is there a JIRA ticket for this as well? (Just getting my tracking up to date, but can't find one)

**Comment by stewsmith** [comment]
@KarenLoughrey pinged you on the ticket

**Comment by KarenLoughrey** [comment]
@stewsmith Translations are done :)

**Pull request merged**
