### PR TITLE
Add Moat to the Partner Directory

### PR DESCRIPTION
**Pull request by clarissabee**
@julieritchie Here's the Moat Partner Directory listing. Just sent you their logo via e-mail! Would love to get this posted as soon as possible. Thanks!

### CODE REVIEW

**Comment by dtothefp** [comment]
@clarissabee @julieritchie this is wrong again. The file `index.hbs` must be inside the `moat` directory. Currently you have a file named `moat` with no extension.

**Comment by clarissabee** [comment]
Sorry about that, I didn't know how to create a folder. How do I fix this?

On Fri, Mar 6, 2015 at 9:19 AM, David Fox-Powell <notifications@github.com>
wrote:

> @clarissabee <https://github.com/clarissabee> @julieritchie
> <https://github.com/julieritchie> this is wrong again. The file index.hbs
> must be inside the moat directory. Currently you have a file named moat
> with no extension.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/optimizely/marketing-website/pull/891#issuecomment-77597452>
> .
>



-- 
*Clarissa Bukhan*
Technology Partnerships | Optimizely, Inc. <http://www.optimizely.com/>
clarissa@optimizely.com  | (415) 609-5097
-------------------------------------------------------------
Web <http://www.optimizely.com/> | LinkedIn
<http://www.linkedin.com/in/clarissabukhan/> | Twitter
<https://twitter.com/clarissa_bee> | Facebook
<http://www.facebook.com/clarissaism>

**Comment by julieritchie** [comment]
@clarissabee @dtothefp hey - looks like you forgot to add /index.hbs to folder name. I created a new one and will close this

**Comment by clarissabee** [comment]
Thank you! I also forgot to note that the KB article link needs to be
updated. I'm waiting on the Education team to send the URL, will get that
to you shortly.

On Fri, Mar 6, 2015 at 10:45 AM, Julie Ritchie <notifications@github.com>
wrote:

> @clarissabee <https://github.com/clarissabee> @dtothefp
> <https://github.com/dtothefp> hey - looks like you forgot to add
> /index.hbs to folder name. I created a new one and will close this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/optimizely/marketing-website/pull/891#issuecomment-77612502>
> .
>



-- 
*Clarissa Bukhan*
Technology Partnerships | Optimizely, Inc. <http://www.optimizely.com/>
clarissa@optimizely.com  | (415) 609-5097
-------------------------------------------------------------
Web <http://www.optimizely.com/> | LinkedIn
<http://www.linkedin.com/in/clarissabukhan/> | Twitter
<https://twitter.com/clarissa_bee> | Facebook
<http://www.facebook.com/clarissaism>

**Comment by julieritchie** [comment]
thanks, @clarissabee just send to me over email

**Pull request closed without merging**
