### PR TITLE
Tyoung/mobile

### PR DESCRIPTION
**Pull request by ihsekat**
On-page SEO optimizations for the mobile product site

### CODE REVIEW

**Comment by ihsekat** [comment]
@stewsmith Just made some basic text changes if you could review. Thanks!

**Comment by stewsmith** [comment]
@ihsekat The changes look good. This is something that needs translation though. You can submit a request for translation [here](https://optimizely.atlassian.net/secure/CreateIssue.jspa?pid=14300&issuetype=3) and follow the instructions [here](https://optimizely.atlassian.net/wiki/pages/viewpage.action?pageId=57770521)

@KarenLoughrey Translation coming your way!

**Comment by ihsekat** [comment]
@KarenLoughrey Thanks you!

@stewsmith Does every change made to the site need to be translated, or can changes be made just to the English site?

**Comment by stewsmith** [comment]
@ihsekat Every change needs to be translated. There are some pages (like Opticon) that we don't translate, but those are not typical.

**Comment by ihsekat** [comment]
@stewsmith Does translation cost money? What if I just want to test something on the US site first for SEO purposes before rolling it out across regions?

**Comment by stewsmith** [comment]
Yes translation costs :moneybag::moneybag::moneybag:. There's really no way to do what you want without translating. If we don't translate those strings, then they show up on foreign pages as english. We also can't use Optimizely here because Google won't index that.

**Comment by ihsekat** [comment]
Ok, do you know how long it takes for them to translate typically? :clock4:

**Comment by ihsekat** [comment]
@stewsmith Actually, I didn't add any new strings, just tweaked existing strings, so can we just keep the existing ones on the international sites and use the new one for the English site?

Also, I don't know German but I know Spanish & Japanese well enough that I can translate a few words. Where would I put these translated strings?

**Comment by stewsmith** [comment]
Translation asks for 2 weeks. 1 week if you're in a rush.

Translation works like a hash map. It takes the exact english as a key then replaces it with the value of the translated string. So if you change the english, even slightly, then it won't find the translated string.

AFAIK this is the translation process.
1) Submit phrase for translation.
2) Processed by EMEA
3) External company translates
4) 2nd external company verifies translations
5) EMEA speakers of language verify translation

Smartling is where we store our translations. Talk to IT about getting access. I doubt you are allowed translate the strings by yourself.

**Comment by ihsekat** [comment]
Can we just assign the old string value to the new key? Is this possible to do in Smartling?

I would really rather not wait 2 weeks every time I make a change to the site. I will be making a lot of small changes in the near future.

**Comment by stewsmith** [comment]
@ihsekat Moving this to email

**Comment by ihsekat** [comment]
@stewsmith Ok thanks. IT says they are not familiar with Smartling and do not have access to it.

**Comment by kylerush** [comment]
@ihsekat why would you be talking to IT about marketing eng stuff?

**Comment by kylerush** [comment]
@ihsekat nevermind, i see stew's comment above. IT doesn't control smartling. arthur and karen do.

**Comment by KarenLoughrey** [comment]
@tyoung @stewsmith The translations are all complete - you can go ahead and merge. Thanks!

**Comment by dtothefp** [comment]
@ihsekat merging

**Pull request merged**
