### PR TITLE
Create index.hbs

### PR DESCRIPTION
**Pull request by mikeapp40**
@julieritchie @kellyfinn please review it. Thanks!

### CODE REVIEW

**Comment by kellyfinn** [comment]
@dtothefp @stewsmith @julieritchie 
I believe this is ready however I don't see Stratigent appearing in the preview. Can you take a look? Thanks.

**Comment by dtothefp** [comment]
@mikeapp40 please name your branch something meaningful like `mappezzato/create-stratigent-partner` and give the PR a more meaningful title than just "create index.hbs"

**Comment by dtothefp** [comment]
@kellyfinn the page was broken I'm thinking because there was a line break in the yml at the quotes but I'm rebuilding to check

screen shot 2015-04-01 at 4 45 20 pm

**Comment by dtothefp** [comment]
retest this please

**Pull request merged**
