### PR TITLE
Updating Title

### PR DESCRIPTION
**Pull request by ihsekat**
Simple title update.

### CODE REVIEW

**Comment by ihsekat** [comment]
@stewsmith Could you review, and ping Karen if this looks good?

**Comment by dtothefp** [comment]
@KarenLoughrey could you please ingest this string into Smartling?

**Comment by KarenLoughrey** [comment]
@dtothefp @ihsekat @stewsmith Translation in progress - should be ready on Monday. @arthuracs I will be out of office on Monday - can you please update this PR once Welocalize confirm they're in?

**Comment by arthuracs** [comment]
@dtothefp @ihsekat @stewsmith Welocalize confirmed that translations are done and live

**Pull request merged**
