### PR TITLE
Krandolph/sec 136 link slash security to bug bounty site

### PR DESCRIPTION
**Pull request by kylerandolph**
Add a link in /security to our Crowdcurity bug bounty platform.

### CODE REVIEW

**Comment by stewsmith** [comment]
I'm getting a 404 on the crowdcurity link. Is that expected?

**Comment by kylerandolph** [comment]
Good question, it is currently set to private, I can confirm that it
actually works and will work for you once I make it public.

**Comment by stewsmith** [comment]
Cool. LGTM once that issue is resolved.

**Comment by kylerandolph** [comment]
Got the greenlight from @stewsmith

**Pull request merged**
