### PR TITLE
Add link to privacy policy to partners forms

### PR DESCRIPTION
**Pull request by yesplease**

### CODE REVIEW

**Comment by stewsmith** [comment]
retest this please

**Comment by stewsmith** [comment]
@yesplease It looks like we do translate these pages.

@KarenLoughrey It seems like we might already have this translated. If not, could you cue it for translation?

**Comment by yesplease** [comment]
@stewsmith thanks for reviewing! How did you know that this page was translated vs not?

**Comment by KarenLoughrey** [comment]
@stewsmith @yesplease Correct, the translation is already there, so this can be merged :)

**Comment by yesplease** [comment]
Thanks Karen!

**Pull request merged**
