### PR TITLE
Update global_feature_list.yml

### PR DESCRIPTION
**Pull request by teeyoutan**
added new vs. returning

### CODE REVIEW

**Comment by dtothefp** [comment]
@teeyoutan what page on the website does this actually effect?

@arthuracs @KarenLoughrey can we get this localized?

**Comment by KarenLoughrey** [comment]
@teeyoutan @dtothefp Translations are in progress; this should be done by Monday. Will confirm as soon as they're ready.

**Comment by stewsmith** [comment]
@dtothefp This effects any page with the feature matrix (/features-and-plans and /pricing).

@KarenLoughrey Thanks for the translation!

**Comment by KarenLoughrey** [comment]
@teeyoutan @stewsmith Translations are ready :)

**Pull request merged**
