### PR TITLE
Update solutions partners industry tags

### PR DESCRIPTION
**Pull request by kellyfinn**
Update tags so that industry filters appear standardized on front end.

### CODE REVIEW

**Comment by kellyfinn** [comment]
@julieritchie Take a look at the preview- check out the industry filters. The duplicates and obvious errors are gone. Let me know if you see anything else you want to change.

**Comment by kellyfinn** [comment]
@julieritchie @stewsmith @dtothefp This is ready, thanks

**Comment by kellyfinn** [comment]
@stewsmith @julieritchie Hi Stew- can we push this live? Thanks!

**Comment by stewsmith** [comment]
@kellyfinn @julieritchie Sorry for the delay. There are some merge conflicts that I need to fix.

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
