### PR TITLE
Updating first paragraph

### PR DESCRIPTION
**Pull request by ihsekat**
Re-writing first paragraph to make it more Google Answer Box-friendly.

### CODE REVIEW

**Comment by ihsekat** [comment]
@KarenLoughrey Could you put in a translation request for this? Thank you!

**Comment by KarenLoughrey** [comment]
@ihsekat Got it! Translations are in progress, hoping to have it back tomorrow. Will keep you posted :)

**Comment by KarenLoughrey** [comment]
@ihsekat Translations are now done!

**Comment by ihsekat** [comment]
Thanks Karen!

**Pull request merged**
