### PR TITLE
Rjohnson/add customer stories

### PR DESCRIPTION
**Pull request by robinjohnson**
@stewsmith - I added one new story to the customer stories page (was planning 2 add a second, but realized we have a few issues with the PDF that we need to resolve before that.

### CODE REVIEW

**Comment by dtothefp** [comment]
@robinjohnson looks like that logo is having a major problem, it's super small

screen shot 2015-04-16 at 11 05 58 am

@arthuracs @KarenLoughrey can we get this localized?

**Comment by KarenLoughrey** [comment]
@robinjohnson @dtothefp Translations are in progress; this should be done by Monday. Will confirm as soon as they're ready.

**Comment by KarenLoughrey** [comment]
@robinjohnson @stewsmith @dtothefp   Translations are all done. However, there seems to be a problem with the Smarter Travel logo, it's really tiny. Is this a problem on .com as well?

**Comment by stewsmith** [comment]
@robinjohnson How is this coming? Last we spoke you getting a new image from design and uploading it to cloudcannon. Need any help with this?

**Comment by stewsmith** [comment]
@robinjohnson pinging this again :dancers:

**Comment by dtothefp** [comment]
@robinjohnson could you please fix this logo issue so we can deploy?

**Comment by robinjohnson** [comment]
@dtothefp - the preview looks good to me. let me know if we're good to go!

**Comment by dtothefp** [comment]
@robinjohnson LGTM merging

**Pull request merged**
