### PR TITLE
Adding new addresses and phone numbers

### PR DESCRIPTION
**Pull request by jrietveld**
Expanded our contact page as we're growing globally. Added phone numbers to all our EMEA offices and added the address of the official German office.

### CODE REVIEW

**Comment by dtothefp** [comment]
@arthuracs @KarenLoughrey @jrietveld should we potentially add some SL_swap tags for these numbers or do you want to list them all?

http://cl.ly/image/0K3D0F2y2p0d

screen shot 2015-04-30 at 1 13 03 pm

**Comment by arthuracs** [comment]
Can this wait until we launch subfolders? Then we can actually add the relevant phone number and address to the relevant regional site.

**Comment by jrietveld** [comment]
This is unrelated to that. This is showing the world we're a global
company. .com is the global site and should show all of this info for all
our offices.

**Comment by arthuracs** [comment]
In that case I'll leave it up to you guys to figure this out. London & Tokyo seem to be missing, and country codes may not be immediately obvious to visitors of the site.

**Comment by jrietveld** [comment]
London office is not in use yet and we don't have a Japanese address or
phone that I or Karen could find.

**Comment by stewsmith** [comment]
@arthuracs @jrietveld What do you want to do with this PR?

**Comment by jrietveld** [comment]
Hi Stewart, please deploy these changes. As soon as new info becomes public
around London and Japan, we'll update the page to include those details as
well. This page should become a representation of our global reach and our
local presence.

Thanks,
Jerry

**Comment by stewsmith** [comment]
LGTM

**Comment by jrietveld** [comment]
LGTM2 thanks!

**Pull request merged**
