### PR TITLE
Removed android coming soon message

### PR DESCRIPTION
**Pull request by julesforrest**
@stewsmith Hey I deleted the asterisk from the pricing.yml file, JIRA ticket MKTG 1481

### CODE REVIEW

**Comment by stewsmith** [comment]
@julesforrest Could you also remove the line that uses the asterisks variable from `website/pricing/index.hbs` (line 70)

**Comment by julesforrest** [comment]
@stewsmith Done

**Comment by stewsmith** [comment]
Sorry @julesforrest I just found more instances of "asterisk".

Could you do a search by running `git grep asterisk` and removing asterisk stuff from the following files?
LMK if you need some assistance.
```
website-guts/assets/css/pages/features-and-plans.scss
website-guts/assets/css/pages/pricing.scss
website/features-and-plans/features.yml
website/features-and-plans/index.hbs
```

**Comment by julesforrest** [comment]
@stewsmith No probs, I think I got em all now

**Comment by stewsmith** [comment]
@kylerush Can you confirm this will not effect the experiment?

**Comment by kylerush** [comment]
@stewsmith it will not affect the experiment. thank you for doing this!

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
