### PR TITLE
Soliver/mob

### PR DESCRIPTION
**Pull request by seanoliver**

### CODE REVIEW

**Comment by stewsmith** [comment]
@KarenLoughrey Could you cue this up for translation?

**Comment by KarenLoughrey** [comment]
@stewsmith @seanoliver Hey! I can get this into translation tomorrow. I noticed that this new string 'Optimizely Developer Docs' is part of the previous string (Optimize code-level variables and roll out entirely new features, no matter how custom your app.') Would you perhaps be able to split this up (i.e. a new string for 'Optimizely Developer Docs') instead? Just keeps the translation memory cleaner? Lmk your thoughts. Thanks!

**Comment by stewsmith** [comment]
@KarenLoughrey I could add an optional link as a separate, smaller string if we're going to be adding other links to these sections. Do you think that's likely @seanoliver ?

**Comment by KarenLoughrey** [comment]
@stewsmith @seanoliver I have sent it for translation anyway and it will be ready tomorrow, so if you want to proceed as is then we'll be ready to go. :)

**Comment by KarenLoughrey** [comment]
@seanoliver @stewsmith Translations are done :)

**Comment by stewsmith** [comment]
lgtm

**Pull request merged**
