### PR TITLE
Update plans_data.yml

### PR DESCRIPTION
**Pull request by teeyoutan**
changed feature name

### CODE REVIEW

**Comment by teeyoutan** [comment]
@KarenLoughrey  please translate then tag @stewsmith when ready to be deployed :)

**Comment by KarenLoughrey** [comment]
@stewsmith Translation in progress, should have it tomorrow. :)

**Comment by KarenLoughrey** [comment]
@stewsmith Translation is done!

**Comment by bhamodi** [comment]
Thanks @teeyoutan and @KarenLoughrey. LGTM.

**Pull request merged**
