### PR TITLE
Updating meta description

### PR DESCRIPTION
**Pull request by ihsekat**

### CODE REVIEW

**Comment by ihsekat** [comment]
@stewsmith My build keeps failing, could you take a look Stew? I'm just trying to update the meta description tag

**Comment by stewsmith** [comment]
@ihsekat Our build is currently broken. I'll review and merge when it's fixed.

**Comment by ihsekat** [comment]
@stewsmith Build seems to be working now, let me know if we're good to merge!

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
