### PR TITLE
Creating a new optimization glossary

### PR DESCRIPTION
**Pull request by ihsekat**

### CODE REVIEW

**Comment by ihsekat** [comment]
@stewsmith Could you review? Also, is there any way I can get the terms centered on the page? Thanks.

**Comment by ihsekat** [comment]
LMK if we're good to merge, @stewsmith!

**Comment by stewsmith** [comment]
@ihsekat 
1. This page doesn't look designed. It lacks visual hierarchy and design patterns.
2. Is there any page linking to this new page?
3. spelling error: "Multivaritae"

I understand you want to move fast but I think this page needs some design and copy love before we deploy, especially if we want this to be a high traffic page.

**Comment by ihsekat** [comment]
Thanks for the feedback @stewsmith. I've fixed the typo.

As far as design, if you can tell me how to center the list of words that should be fine for now. The page will eventually be linked to from the resources page and will eventually have its own template designed for it, but right now we just need a MVP live that links to our existing content pages.

**Comment by stewsmith** [comment]
cc @tgiglio

**Comment by stewsmith** [comment]
Closing this PR in favor of https://github.com/optimizely/marketing-website/pull/1309

**Pull request closed without merging**
