### PR TITLE
Soliver/integrations pricing link

### PR DESCRIPTION
**Pull request by seanoliver**

### CODE REVIEW

**Comment by bhamodi** [comment]
retest this please

**Comment by bhamodi** [comment]
Will this new text require translations? @seanoliver @KarenLoughrey

**Comment by KarenLoughrey** [comment]
@seanoliver @yesplease Thanks Bradley, yes, it does need translation. I have put it into translation and hope to have this ready tomorrow - will keep you posted.

**Comment by KarenLoughrey** [comment]
@yesplease @seanoliver Translations are done :)

**Comment by bhamodi** [comment]
LGTM.

**Pull request merged**
