### PR TITLE
Updated Lytics text and link

### PR DESCRIPTION
**Pull request by kellyfinn**

### CODE REVIEW

**Comment by kellyfinn** [comment]
This is ready @dtothefp @julieritchie @stewsmith

**Comment by stewsmith** [comment]
@kellyfinn @julieritchie Can we just use www.getlytics.com as the display link?

It's showing up like this is tablet.

**Comment by kellyfinn** [comment]
I've updated the link, thanks!

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
