### PR TITLE
Add partner to Partner Directory: Wdecker/partnerdirectory add uservalue

### PR DESCRIPTION
**Pull request by WernerDH**
@kellyfinn hey kelly, this is the PR for solution partner Uservalue.

Cheers,
Werner

### CODE REVIEW

**Comment by kellyfinn** [comment]
@dtothefp @stewsmith Can you guys take a look at the preview? The partner detail page isn't loading properly for me. Thanks for the help!

**Comment by dtothefp** [comment]
@WernerDH @kellyfinn this is using the old template type. If you see `layout: partners.hbs` should not have the `.hbs` extension and there are no translation keys or `MD_page_content: true` at the bottom

Please confirm with me that you understand the problem and I will go ahead and fix it

**Comment by dtothefp** [comment]
works with new syntax, merging

**Comment by WernerDH** [comment]
Yes confirmed. Thanks for pointing this out David!

**Pull request merged**
