### PR TITLE
Added What Is iOS A/B Testing SEO page

### PR DESCRIPTION
**Pull request by robinjohnson**
added new page

### CODE REVIEW

**Comment by robinjohnson** [comment]
@srusonis

**Comment by robinjohnson** [comment]
@stewsmith - Hi Stew! We added a new SEO page under resources but it won't show in preview. Can you take a look? Right now, preview takes me to the Optimizely homepage.

**Comment by stewsmith** [comment]
yo @robinjohnson! Looking now.

**Comment by stewsmith** [comment]
I'm seeing the page here:
http://optimizely-marketing-site-staging.s3-website-us-east-1.amazonaws.com/rjohnson/resources-seo-ios/resources/ios-ab-testing/

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
