### PR TITLE
Update index.hbs

### PR DESCRIPTION
**Pull request by heatherswatkins**
Hey @stewsmith - I updated some text for the demo page.

### CODE REVIEW

**Comment by stewsmith** [comment]
Thanks @heatherswatkins 

@KarenLoughrey  Can you ingest this for translation? Thanks!

**Comment by KarenLoughrey** [comment]
@heatherswatkins @stewsmith Translations in progress! I am expecting them Monday and will confirm as soon as they're done. :)

**Comment by KarenLoughrey** [comment]
@heatherswatkins @stewsmith Today (Monday) is a bank holiday in Japan, and we weren't able to get translations on Friday. So, this should be ready tomorrow, and I will confirm as soon as the strings are available.

**Comment by stewsmith** [comment]
Sounds good, thanks @KarenLoughrey :earth_asia:

**Comment by KarenLoughrey** [comment]
@heatherswatkins @stewsmith Translations are done!

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
