### PR TITLE
Use the new LEGO NPM module that supports semantic versioning.

### PR DESCRIPTION
**Pull request by danoc**
@stewsmith – Can you pull this one, run `rm -rf node_modules/lego`, `npm install` and then see if you dev environment works? Mine is all borked right now.

### CODE REVIEW

**Comment by stewsmith** [comment]
@danoc Getting this error:
`Fatal error: Cannot find module 'path-is-absolute'`

**Comment by danoc** [comment]
That seems like it would be totally unrelated. I'll stop by at some point.

Did you do NPM install first?

**Comment by stewsmith** [comment]
ya followed your instructions. Lets get your environment unborked too.

**Comment by stewsmith** [comment]
That was an accident

**Comment by danoc** [comment]
Hahah so it LGTY?

**Comment by stewsmith** [comment]
@danoc Just ran again and all worked well. I think there was an unrelated dependency issue.

Anything I'm looking for specifically?

**Comment by danoc** [comment]
Nah just make sure that LEGO still loads/works but it seems like it did.

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
