### PR TITLE
Opticon Homepage Ad

### PR DESCRIPTION
**Pull request by stewsmith**
Adds an advertisement for Opticon on www.optimizely.com

### CODE REVIEW

**Comment by tomgenoni** [comment]
LGTM

**Comment by arthuracs** [comment]
@stewsmith @dtothefp @KarenLoughrey 
This also appears on all international website now, untranslated. E.g. https://www.optimizely.jp/?optimizely_disable=true

I've removed it for now with an Optimizely experiment (https://app.optimizely.com/edit?experiment_id=2856970262)

**Comment by KarenLoughrey** [comment]
Thanks @arthuracs. We might actually want this for EMEA as we're pushing for international attendees - will check with @jrietveld and Fabian/Anoma!

**Comment by arthuracs** [comment]
Per request from EMEA marketing, showing these untranslated on .de / .es / .fr. Still hiding it for .jp.

**Pull request merged**
