### PR TITLE
Rpam/stats copy cleanup

### PR DESCRIPTION
**Pull request by robinpam**
Made a lot of changes:

- Capitalized Internet in Hero area
- Capitalized Stats Engine in "Interested in how Stats Engine affects your results" in error graphic section
- Capitalized Engine in "Leave the stats to us" section at the bottom of the page
- Fixed typo in footnote (continous --> continuous)

Need to coordinate changes with @KarenLoughrey for translation purposes. Should not  be pushed live before translation occurs

### CODE REVIEW

**Comment by stewsmith** [comment]
@robinpam I'm pulling this down now and fixing the conflict

**Comment by dtothefp** [comment]
@stewsmith I just fixed that conflict. @robinpam we can't merge this until @KarenLoughrey  get's it translated, I just spoke with here about it

**Comment by robinpam** [comment]
@stewsmith @dtothefp Yep, no major rush on these items, just wanted to get them in @KarenLoughrey 's translation queue.

**Comment by robinpam** [comment]
Made an additional change to the error graphic section, to update the copy in the right-hand section. Old copy: WITH TRADITIONAL STATISTICS setting a 95% significance level can result in a 30% or more chance you'll make the wrong decision if you don't avoid pitfalls*

New copy: WITH TRADITIONAL STATISTICS setting a 95% significance level results in a <70% chance you'll make the right decision if you don't avoid pitfalls*

**Comment by arthuracs** [comment]
@dtothefp Not sure what's causing this in this PR but the footnote p element is not being opened properly (<p class="footnote"* We simulated millions vs. <p class="footnote">* We simulated millions). Looks like Chrome corrects for it on its own, but Smartling doesn't like it when ingesting so the layout gets messed up on the translated version. See screenshots.
view-source_optimizely-marketing-site-staging_s3-website-us-east-1_amazonaws_com_rpam_stats-copy-cleanup_statistics_
optimizely_stats_engine_and_optimizely_stats_engine

**Comment by robinpam** [comment]
@KarenLoughrey Heads up, @dtothefp caught a typo (missing word) in the error graphic section. It should have the word "chance" in the right hand section. Sending you an email as well.

**Comment by KarenLoughrey** [comment]
@dtothefp @robinpam Translations are now complete, so this is ready to go :)

**Pull request merged**
