### PR TITLE
Add back plans content

### PR DESCRIPTION
**Pull request by stewsmith**
Adds back a `Contact Sales` button and `Contact Sales` bottom paragraph.

### CODE REVIEW

**Comment by stewsmith** [comment]
@KarenLoughrey Could you turn this into other languages!?!? :sake:

**Comment by KarenLoughrey** [comment]
@stewsmith On. It. Should be ready tomorrow. :) :ear_of_rice:

**Comment by yesplease** [comment]
thanks @KarenLoughrey !

**Comment by KarenLoughrey** [comment]
@yesplease Translations are done :)

**Pull request merged**
