### PR TITLE
adding communities to the list of benefits

### PR DESCRIPTION
**Pull request by chestone**
Added a link to the new communities page to the existing jobs page. Let me know what you think!

### CODE REVIEW

**Comment by chestone** [comment]
cc @stewsmith @dtothefp

**Comment by yjkogan** [comment]
LGTM, though it's not my call :p

**Comment by stewsmith** [comment]
Hey @chestone the communities looks off on mobile and tablet. Please keep in mind we write min-width media-queries! :camel:

**Comment by chestone** [comment]
Moved to another PR here https://github.com/optimizely/marketing-website/pull/776 closing

**Pull request closed without merging**
