### PR TITLE
Update feature_list.yml

### PR DESCRIPTION
**Pull request by teeyoutan**
changing copy within the feature matrix

### CODE REVIEW

**Comment by stewsmith** [comment]
@KarenLoughrey Hey Karen, this PR is ready for translation. I'm also submitting a JIRA ticket via the new protocol!!

**Comment by dtothefp** [comment]
@teeyoutan @kylerush Is this approved? I know we are running experiments on the pricing page. Will content change potentially effect experiment accuracy?

**Comment by stewsmith** [comment]
@dtothefp Good thinking. According to @kylerush, this will not effect the experiment.

**Comment by dtothefp** [comment]
@KarenLoughrey is this ready?

**Comment by arthuracs** [comment]
These just came back! All ready to go.

**Pull request merged**
