### PR TITLE
Wdecker/solution partners dach

### PR DESCRIPTION
**Pull request by WernerDH**
@julieritchie  dear julie, these are the new solution partners for the dach region. please review and let me knoe if anything needs correcting. cheers, werner

### CODE REVIEW

**Comment by stewsmith** [comment]
@julieritchie What's the status on this? Can you review?

Thanks!

**Comment by julieritchie** [comment]
@stewsmith we have a sla with these. I've spoken to Kyle and we're aligned on this :)

**Comment by dtothefp** [comment]
@julieritchie what's the status on this?

**Comment by WernerDH** [comment]
@julieritchie  Hey Julie, is this branch ready to go live today? please let me know if anything is still needed. (partners are pinging me already and get somewhat concerned)

**Comment by dtothefp** [comment]
@kellyfinn can you review, sounds like this is time sensitive. @WernerDH do any of these have links to external articles that should be in `kb_article`

**Comment by WernerDH** [comment]
Hi David, thanks for picking this up.  (yes, it is time sensitive) These PD
entries are standard entries. Not sure what is meant with kb_article?

Viele Grüße,
Werner Decker




*Werner Decker*
Strategic Partnerships EMEA
Phone: +31 (0) 20 80 85 01 3
werner@optimizely.com | www.optimizely.com


*Want to partner with Optimizely? Get all the details here
<http://www.optimizely.com/partners/solutions>.*

**Comment by dtothefp** [comment]
@WernerDH `kb_article` is a link to an external article for the partner. It will be linked to from this button

screen shot 2015-03-17 at 2 42 17 pm

If `kb_article` is blank the button will not show which is no problem

**Comment by WernerDH** [comment]
Ah ok, thanks for letting me know. Well, nope there is no KD_article
included in any of these new partner entries. Let me know if you need
anything else before taking these online.

Viele Grüße,
Werner Decker




*Werner Decker*
Strategic Partnerships EMEA
Phone: +31 (0) 20 80 85 01 3
werner@optimizely.com | www.optimizely.com


*Want to partner with Optimizely? Get all the details here
<http://www.optimizely.com/partners/solutions>.*

**Comment by julieritchie** [comment]
@dtothefp @WernerDH It looks like these are all solutions partners so a KB article is not necessary. FYI - this is noted already in the partner editing guide. let me know if I'm missing something

**Comment by WernerDH** [comment]
Yes, these are all solution partners and a KB article is not necessary.

Viele Grüße,
Werner Decker




*Werner Decker*
Strategic Partnerships EMEA
Phone: +31 (0) 20 80 85 01 3
werner@optimizely.com | www.optimizely.com


*Want to partner with Optimizely? Get all the details here
<http://www.optimizely.com/partners/solutions>.*

**Comment by stewsmith** [comment]
@WernerDH @julieritchie In the future please use <50 priority with 1 star partners. I've made that correction.

LGTM :+1:

**Pull request merged**
