### PR TITLE
Create index.hbs

### PR DESCRIPTION
**Pull request by lisathoman**
@julieritchie @kellyfinn

### CODE REVIEW

**Comment by lisathoman** [comment]
@julieritchie @kellyfinn  Pls review! Did I do this right?

**Comment by dtothefp** [comment]
@lisathoman thanks for this. Also, in the future could you make a more descriptive title and branch name for your PR like `lthoman/create-sellpoints-solution-partner` and the title could be something the similar
#### Creat Sell Points solutions partner page

Also, please make sure that when you create a directory/folder for the `index.hbs` it should be always lowercase and if it's two words sepearated by dashes. This becomes the visible route on the website so we should be careful about this syntax. Your partner would look like

`https://www.optimizely.com/partners/solutions/SellPoints`

whereas we want 

`https://www.optimizely.com/partners/solutions/sell-points`

If you haven't already please download the Optimizely Chrome Extension that allows you to preview your branch by clicking this button

All info for Chrome Extension is here
https://docs.google.com/document/d/1JmR3PtoiSyxbAxUY6PvP3Z9jv2qy3_MzDz-31zZicAQ/edit?usp=sharing

And your branch preview is here

**Comment by dtothefp** [comment]
retest this please

**Comment by kellyfinn** [comment]
This is ready @julieritchie @dtothefp @stewsmith

**Comment by dtothefp** [comment]
@kellyfinn could you please look at my above comments for future reference? For these kinds of problems I will have to pull down the branch and make manual changes.

**Comment by julieritchie** [comment]
@dtothefp is the best way to fix this copy/paste the info in the pull request and make a new branch/pull request? If the mistake has already been made by the time it gets to Kelly what's the best fix?

**Comment by dtothefp** [comment]
@julieritchie the best to do at that point is just for me to fix it. It is not easy in the github GUI to change directory names.  I'm merging this :smile:

**Pull request merged**
