### PR TITLE
MKT-2196 -- change homepage headline copy

### PR DESCRIPTION
**Pull request by stewsmith**
https://optimizely.atlassian.net/browse/MKT-2196

### CODE REVIEW

**Comment by stewsmith** [comment]
@KarenLoughrey pinging for translation.

**Comment by KarenLoughrey** [comment]
@stewsmith Thanks! I will send this for translation, and I will also have this reviewed by our in-house teams. This means it might take a little longer than usual, but I am aiming to have it ready Monday. Will keep you posted!

**Comment by stewsmith** [comment]
@KarenLoughrey Sounds good, thanks!

**Comment by KarenLoughrey** [comment]
@stewsmith All good to go! :)

**Pull request merged**
