### PR TITLE
Create smart-internet-media

### PR DESCRIPTION
**Pull request by MartijnJanssen**

### CODE REVIEW

**Comment by stewsmith** [comment]
Hey @MartijnJanssen what is the status of this PR? Is it ready for content review?

**Comment by MartijnJanssen** [comment]
Yep, in my opinion all details should be ok!

**Comment by stewsmith** [comment]
Hey @kellyfinn @julieritchie Can you review this?

**Comment by julieritchie** [comment]
@MartijnJanssen hey there - just remember to add the "content review" label when its ready for review. Thanks!

**Comment by MartijnJanssen** [comment]
@julieritchie  Ah missed one step in the guide. Will do so next time, thanks!

**Comment by stewsmith** [comment]
@julieritchie Can you let me know when this is ready for eng review? Thanks!

**Comment by kellyfinn** [comment]
@stewsmith 
I believe this is ready to go, but I don't see the partner appearing on the staging site to confirm the listing. I've tried a few times to preview changes and it's not there for me. Can you take a look? Thanks for the help!

**Comment by stewsmith** [comment]
@kellyfinn I'll let @dtothefp know about this as he's deploy captain this week

**Comment by dtothefp** [comment]
@kellyfinn @MartijnJanssen this will not work because the file is named `/smart-internet-media`. Essentially this is the directory name without a file extension. The proper file name should be `/smart-internet-media/index.hbs`. I will pull it down and change it because this isn't something that can be fixed in the GitHub interface.

**Comment by dtothefp** [comment]
@kellyfinn please see my changes to filename. I'm going to merge this

**Comment by MartijnJanssen** [comment]
hey @dtothefp @kellyfinn Thanks for the help so far! 

Noticed one more thing, based on the input in the sheet by the partner, I have stated Region as "The Netherlands". Probably should be "EMEA - Netherlands" to get it listed correctly? What is the quickest way to change this now?

**Comment by kellyfinn** [comment]
@MartijnJanssen Looks like Smart Internet Media appers when users select "EMEA- Netherlands" in the Region filter, so I don't think we need to change it from Netherlands to EMEA - Netherlands. Was there another reason to update it? I can go ahead and file a PR to update it if so.

**Comment by MartijnJanssen** [comment]
@kellyfinn Yep, it probably has been solved, no more action needed! THANKS!

**Pull request merged**
