### PR TITLE
Adding the London office address and updating the NL and DE phone #s

### PR DESCRIPTION
**Pull request by jrietveld**
Hey guys,

I've just added the London address and updates some phone numbers. 

Cheers,
Jerry

### CODE REVIEW

**Comment by yesplease** [comment]
howdy @jrietveld -- I didn't see this until just now. I just pushed an update to this page. I will incorporate your changes here but will close this PR.

**Comment by jrietveld** [comment]
Hi @yesplease thanks for pushing these changes. I noticed some things changed about the listing.

* It would be best to keep the labeling consistent so in stead of UK office I would prefer **London Office**, in line with the other ones. 
* The street name should be **Eastcastle** as one word, not two.

Thanks a mill!
Jerry

**Comment by yesplease** [comment]
Sure thing, @jrietveld -- I had built it out as per Anoma's request in the Jira ticket but am happy to make these updates, which I see you had included in your original PR anyway.

Cheers!

**Comment by jrietveld** [comment]
Awesome, thanks!

On Thu, Jul 9, 2015 at 5:49 PM, Bradley Heinz <notifications@github.com>
wrote:

> Sure thing, @jrietveld <https://github.com/jrietveld> -- I had built it
> out as per Anoma's request in the Jira ticket but am happy to make these
> updates, which I see you had included in your original PR anyway.
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/optimizely/marketing-website/pull/1256#issuecomment-120044590>
> .
>



-- 
*Jerry Rietveld*
European Marketing Manager UK / Nordics / Benelux | Optimizely.com
<http://www.optimizely.com/>
jerry@optimizely.com | +44 (0) 20 3318 0636  | @optimizely
<https://twitter.com/optimizely>

*As featured in:*
Venture Beat
<http://venturebeat.com/2014/10/01/marketing-tech-50b-in-investment-but-top-tools-have-only-4-1-penetration/>
- Forbes
<http://www.forbes.com/sites/parmyolson/2015/01/21/jawbone-guinea-pig-economy/>
- Wired <http://www.wired.com/2012/04/ff_abtesting/> - Bloomberg TV
<http://bit.ly/Bloomberg13> - Dublin Web Summit
<http://bit.ly/WebSummit2015>

**Pull request closed without merging**
