### PR TITLE
Removing header

### PR DESCRIPTION
**Pull request by ihsekat**
Removing extra header, optimizing for Google Answer Box

### CODE REVIEW

**Comment by ihsekat** [comment]
@KarenLoughrey Very minor changes, but could you put in a translation request for me?

**Comment by ihsekat** [comment]
@stewsmith @yesplease Any idea why the checks for this haven't completed yet?

**Comment by stewsmith** [comment]
@ihsekat One of our staging builds got held up and blocked the build queue. I've fixed the problem so this should build shortly.

**Comment by KarenLoughrey** [comment]
@ihsekat Turns out we already have these translations in the translation memory, so this is ready to go! :)

**Comment by ihsekat** [comment]
Thanks Karen!

**Comment by yesplease** [comment]
LGTM

**Comment by yesplease** [comment]
Oops, looks like you merged as I was reviewing, @ihsekat

**Comment by stewsmith** [comment]
@ihsekat Bradley speaks the truth. Please do not merge without review as it can break the site.

**Pull request merged**
