### PR TITLE
Fresh Egg AU Solution Partner

### PR DESCRIPTION
**Pull request by dtothefp**
@Hiliaryrobertson @stewsmith @kellyfinn I migrated https://github.com/optimizely/marketing-website/pull/971 to here because it was being merged into the wrong location

### CODE REVIEW

**Comment by dtothefp** [comment]
@kellyfinn can you please add the logo? @stewsmith I created this as a new branch and updated to new Assemble syntax

**Comment by stewsmith** [comment]
@kellyfinn Could you take a look at this PR? Thanks!

**Comment by kellyfinn** [comment]
@dtothefp @stewsmith 
I'm not sure why the logo isn't appearing for me in the preview. Thanks for taking a look. Also FYI we will be merging listings such as these that are listed multiple times for various locations into one single listing.  For example, Fresh Egg has a UK listing already, so this will be the second location. We can address this after we get it live though, since we have a few details still to work out. Thanks.

**Comment by dtothefp** [comment]
@kellyfinn logo works for me. As you mentioned looks kind of crappy with two of the same logos next to one another

screen shot 2015-04-16 at 11 11 30 am

**Pull request merged**
