### PR TITLE
Srusonis/resources page update

### PR DESCRIPTION
**Pull request by srusonis**
Hey @stewsmith can you check out these updates to the Resources page?

### CODE REVIEW

**Comment by srusonis** [comment]
Ok, we're missing one of the resources. Hold up

**Comment by stewsmith** [comment]
LGTM

**Comment by dtothefp** [comment]
@stewsmith @srusonis I don't think marketers should be merging their own branch. Please only have marketing eng merge branches in the future. On top of that it looks as if the tests for the branch failed and it was still merged. What's up with that?

**Comment by stewsmith** [comment]
@dtothefp This was merged accidentally and I stopped the build.

**Comment by dtothefp** [comment]
@stewsmith I accidentally deleted this branch because I was typing this message on my phone this morning and my fat fingers got in the way

**Comment by srusonis** [comment]
@dtothefp Thanks for deleting the branch - @stewsmith, would you typically do that, or should I do it after the branch gets merged?

and yep, like Stew mentioned, I accidentally merged the branch. Not normal protocol. Usually Stew does it once he signs off on the update.

**Comment by stewsmith** [comment]
@srusonis Yes I would normally delete the branch.

**Comment by dtothefp** [comment]
@srusonis I put a content review label on this.  Is this ready for "Eng Review"?

**Pull request merged**
