### PR TITLE
Updating copy

### PR DESCRIPTION
**Pull request by ihsekat**
Updating copy to optimize for SEO & readability

### CODE REVIEW

**Comment by ihsekat** [comment]
@KarenLoughrey Could you put in a translation request for this? Thanks!

**Comment by KarenLoughrey** [comment]
@ihsekat  Translations are in progress :) Hoping to have them back on Monday. Will update you as soon as they're ready.

**Comment by KarenLoughrey** [comment]
@ihsekat Today (Monday) is a bank holiday in Japan, and we weren't able to get translations on Friday. So, this should be ready tomorrow, and I will confirm as soon as the strings are available.

**Comment by ihsekat** [comment]
Ok thanks for the update, @KarenLoughrey!

**Comment by KarenLoughrey** [comment]
@ihsekat Translations are done! :)

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
