### PR TITLE
New technology partner: Decibel Insight

### PR DESCRIPTION
**Pull request by kellyfinn**

### CODE REVIEW

**Comment by kellyfinn** [comment]
This is ready @stewsmith @julieritchie

**Comment by stewsmith** [comment]
@julieritchie @kellyfinn The logo is really grainy. @julieritchie Are you cool with that?

Code LGTM, we're going to wait until later in the day to deploy to help with the investigation of https://optimizely.atlassian.net/browse/AI-398

**Comment by kellyfinn** [comment]
@stewsmith @julieritchie I updated the logo with a new one I found. Thanks!

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
