### PR TITLE
Adding a link to the communities page from jobs

### PR DESCRIPTION
**Pull request by chestone**

### CODE REVIEW

**Comment by chestone** [comment]
cc @stewsmith @kylerush

**Comment by chestone** [comment]
@stewsmith I believe I've addressed your concerns with the mobile/tablet versions with my update. Check it out :)

**Comment by dtothefp** [comment]
@chestone LGTM, thanks for your work on this.  I'll go ahead and merge

**Comment by stewsmith** [comment]
@chestone Nailed it. Thanks!

**Pull request merged**
