### PR TITLE
Update global_feature_list.yml

### PR DESCRIPTION
**Pull request by teeyoutan**

### CODE REVIEW

**Comment by teeyoutan** [comment]
@KarenLoughrey  please localize change and tag stew and change label to eng review when ready .

**Comment by KarenLoughrey** [comment]
Hey @teeyoutan , @stewsmith  Sorry for the delay, just back from holiday. Translations are now in progress and will let you know as soon as they're ready. Hopefully tomorrow!

**Comment by KarenLoughrey** [comment]
@teeyoutan @stewsmith Translations are done :) Localization freeze label can be removed. Cheers!

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
