### PR TITLE
Srusonis/resources-mvt-update

### PR DESCRIPTION
**Pull request by srusonis**
Updating copy on "What is multivariate testing?" SEO page under Resources

### CODE REVIEW

**Comment by srusonis** [comment]
Hey there @stewsmith! Happy Friday!

Can you check out some changes that Robin and I are working on for the SEO pages?

This PR has updates to "What is Multivariate Testing?" and a new page, "What is Website Optimization?"

Thanks!

**Comment by stewsmith** [comment]
hey @srusonis Happy to see you cruising with GH. I'll check these Pull Requests out this afternoon!

**Comment by srusonis** [comment]
awesome, thanks @stewsmith

**Comment by stewsmith** [comment]
Looks like the page isn't displaying properly in [the preview](http://optimizely-marketing-site-staging.s3-website-us-east-1.amazonaws.com/srusonis/resources-mvt-update/resources/multivariate-testing/). I'm looking into it now.

**Comment by stewsmith** [comment]
@srusonis I just corrected a small spacing issue that was preventing your changes from building.

Could you take a look at the previews for the [multivariate-testing](http://optimizely-marketing-site-staging.s3-website-us-east-1.amazonaws.com/srusonis/resources-mvt-update/resources/multivariate-testing/) and the [website-optimization](http://optimizely-marketing-site-staging.s3-website-us-east-1.amazonaws.com/srusonis/resources-mvt-update/resources/website-optimization/) pages and confirm your changes are correct?

Thanks!

**Comment by srusonis** [comment]
Cool, thanks @stewsmith. Looking good to me, but I'm walking Steve through these tomorrow morning to make sure he gives them the thumbs up.

**Comment by srusonis** [comment]
@stewsmith We're good to go! Thanks for your help with this project.

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
