### PR TITLE
Rjohnson

### PR DESCRIPTION
**Pull request by robinjohnson**
Added mobile ebook to the resources page.

### CODE REVIEW

**Comment by robinjohnson** [comment]
@srusonis - could you review this request? thank you!

**Comment by srusonis** [comment]
LGTM. 

@stewsmith Howdy! Can you check Robin's work to make sure it's clear to merge?

**Comment by kylerush** [comment]
@srusonis @robinjohnson we started using the "eng review" label for pull requests that need eng review. this gives us a bird's eye view of where each pull request is. still a good idea to comment the deploy captain to get review.

**Comment by stewsmith** [comment]
Hey @robinjohnson almost a :100: 
A few things:
1) Branches should be named like so: `rjohnson/terse-description`
2) Please [name your PR](http://cl.ly/image/1q1j0M301s2m) something descriptive.
3) [These are the files you had before](http://cl.ly/image/151q0m1d0J0k).  The first file is the correct content but the wrong file naming structure. The second file is the correct file naming structure, but it's empty.
4) You should preview and verify your PR is correct by using the Optimizely Preview plugin.

These corrections were easy to make so I went ahead and made them.

**Comment by stewsmith** [comment]
LGTM :statue_of_liberty:

**Pull request merged**
