### PR TITLE
Added new stories and removed churned customers

### PR DESCRIPTION
**Pull request by robinjohnson**
These changes are part of the transition to HTML landing pages. I added several new stories, removed a few stories, and changed the CTA button text on all to "Learn More"

Still need to add URL links for all new additions.

### CODE REVIEW

**Comment by robinjohnson** [comment]
@stewsmith - HEYO! can you look this over and see if it looks alright? we still need to add URLs for the new html pages once we have them. thanks!

**Comment by stewsmith** [comment]
Thanks for the PR @robinjohnson ! This PR will have to go in at the same time as scribe, but I'll look it over before then.

**Comment by srusonis** [comment]
@robinjohnson Can you add the Obama 2012 story to the page?

Here are the three stats being called out: 
500+ A/B Tests Run
49% Increase in Donations
161% Improvement in Email Sign Ups

@stewsmith We'd like to be able to tag Karen on this PR to have her start the translation process for this page. Does that sound good? New at this, so I'm not sure of the exact pre-launch translation process.

**Comment by stewsmith** [comment]
@srusonis you got it!

@KarenLoughrey Can you start translation for this PR? Thanks!

**Comment by srusonis** [comment]
@stewsmith @KarenLoughrey thanks!

**Comment by KarenLoughrey** [comment]
@stewsmith @robinjohnson @srusonis I am having problems ingesting this content. When I go to the staging page, all I see is the Chrome Industries video and description: 
image

Any idea why this might be?

**Comment by stewsmith** [comment]
Hey @KarenLoughrey looks like there's an error in the yaml formatting. I'm looking into it now.

**Comment by stewsmith** [comment]
@KarenLoughrey This is fixed. Sorry about the delay!

**Comment by KarenLoughrey** [comment]
@stewsmith @robinjohnson @srusonis Got it, thanks! :) Translations are in progress. I'm hoping to get it tomorrow, and will keep you posted.

**Comment by srusonis** [comment]
@KarenLoughrey thanks for the update!

**Comment by KarenLoughrey** [comment]
@robinjohnson @stewsmith @srusonis Translations are done! :)

**Comment by srusonis** [comment]
Thanks, @KarenLoughrey!

@robinjohnson We have a URL structure for the new pages - I'll send you an email with instructions. Should be pretty straightforward to update in this PR.

**Comment by stewsmith** [comment]
Closing this in favor of https://github.com/optimizely/marketing-website/pull/1299

**Pull request closed without merging**
