### PR TITLE
Bing Webmaster Tools Verification

### PR DESCRIPTION
**Pull request by ihsekat**
Ownership verification for Bing Webmaster Tools

### CODE REVIEW

**Comment by ihsekat** [comment]
@stewsmith could you take a look to make sure everything is good?

**Comment by dtothefp** [comment]
@ihsekat do you want this `meta` tag only on the homepage or on all pages?

**Comment by ihsekat** [comment]
@dtothefp Only on the homepage.

**Comment by dtothefp** [comment]
@ihsekat LGTM

**Pull request merged**
