### PR TITLE
Create index.hbs

### PR DESCRIPTION
**Pull request by mikeapp40**
@julieritchie @kellyfinn please review this! Thx.

### CODE REVIEW

**Comment by stewsmith** [comment]
retest this please

**Comment by stewsmith** [comment]
@kellyfinn Hey Kelly, what is the status of this PR?

**Comment by kellyfinn** [comment]
@dtothefp @stewsmith @julieritchie 
This is ready, thanks!

**Comment by dtothefp** [comment]
@stewsmith this is good to go with new Assemble syntax

**Comment by stewsmith** [comment]
LGTM

**Pull request merged**
